remote_theme: BDHU/minimalist
color-scheme: auto/dark
title: Omkar B. Shende
description: My site
logo: ./assets/images/profile.jpeg
sidebar:
  - name: Google Scholar
    icon: <i class="fa-solid fa-book-open"></i>
    link: https://scholar.google.com/citations?user=LCY03RAAAAAJ&hl
  - name: CV
    icon: <i class="fa-solid fa-file-pdf"></i> 
    link: ./assets/docs/ShendeOmkarCV.pdf
  - name: Email
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:oshende@stanford.edu
