remote_theme: BDHU/minimalist
color-scheme: dark
title: Omkar B. Shende
description: Computational scientist
logo: ./assets/images/profile.jpeg
google_analytics: G-ENZEGQ985T
favicon: true
sidebar:
  - name: Google Scholar
    icon: <i class="fa-solid fa-book-open"></i>
    link: https://scholar.google.com/citations?user=LCY03RAAAAAJ&hl
  - name: CV
    icon: <i class="fa-solid fa-graduation-cap"></i> 
    link: ./assets/docs/ShendeOmkarCV.pdf
  - name: Email
    icon: <i class="fa-solid fa-inbox"></i>
    link: mailto:oshende@stanford.edu
