remote_theme: BDHU/minimalist
color-scheme: auto/dark
title: Omkar B. Shende
description: 
logo: ./assets/images/profile.jpeg
sidebar:
  - name: Google Scholar
    icon: <i class="fa-solid fa-user"></i>
    link: 
  - name: Curriculum Vitae
    icon: <i class="fa-solid fa-file-pdf"></i> 
    link: ./assets/docs/ShendeOmkarCV.pdf
  - name: Email
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:oshende@stanford.edu
